repos:
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1          
    hooks:
      - id: ruff
        args: [--fix]    

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic[mypy]==2.11.7"  

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system         
        entry: .venv/bin/python -m pytest -q
        pass_filenames: false  