# pyproject.toml
[tool.ruff]
target-version = "py311"      
line-length     = 100         
exclude         = [
    "__pypackages__",
    ".venv",
    "build",
    "dist",
]
select = [
    "E",   # pycodestyle 
    "F",   # pyflakes
    "I",   # isort
    "B",   # bugbear 
    "UP",  # pyupgrade 
]